### PR TITLE
Updated to work with python3

### PR DESCRIPTION
**Pull request by chamilton-ccn**
Updated to work with python3

### CODE REVIEW

**Comment by lgedgar** [comment]
Wow, had no idea this project was found useful by anyone besides myself...  I suppose should remove this from GitHub though as its new home is at https://kallithea.rattailproject.org/rattail-project-contrib/sqlalchemy-pervasive

That "upstream" repo already contains Python 3 support I believe, and 0.1.3 is available on [PyPI](https://pypi.org/project/sqlalchemy-pervasive/0.1.3/) as well.  So I'm not sure if this PR is even needed, but if it is I'd rather see it happen elsewhere.  Let me know what you think?

**Comment by chamilton-ccn** [comment]
>Wow, had no idea this project was found useful by anyone besides myself... 

Yeah, on occasion I have to extract data from Pervasive databases and this is super-helpful :-)

>That "upstream" repo already contains Python 3 support I believe, and 0.1.3 is available on PyPI as well. So I'm not sure if this PR is even needed, but if it is I'd rather see it happen elsewhere. Let me know what you think?

Interesting. GitHub was the only place I've ever seen this repo. My pull request is most likely not needed then, if the upstream repo you linked already supports python3. I'll probably maintain my own fork of this on GitHub, but I'm definitely going to pull from upstream (I hope you don't mind). Thanks again for creating this.

**Comment by lgedgar** [comment]
Cool I've just pushed a new release (0.2.1) to [PyPI](https://pypi.org/project/sqlalchemy-pervasive/) so the project should be Python 3 only now, and have the updated home page listed...  I have no problems with your plan; let me know if you need anything else from me.

**Comment by chamilton-ccn** [comment]
> Cool I've just pushed a new release (0.2.1) to [PyPI](https://pypi.org/project/sqlalchemy-pervasive/) so the project should be Python 3 only now, and have the updated home page listed... I have no problems with your plan; let me know if you need anything else from me.

Will do, thanks again!

**Comment by yekibud** [comment]
@lgedgar FWIW, I think keeping un-official forks maintained on Github is probably a good idea if you want people to find your projects.  For better or worse, it's sort of the default search engine for FOSS projects.  Could even just be empty repos with a README pointing at the official upstream.

**Comment by lgedgar** [comment]
@yekibud I agree on a practical level you're right, but I remain uninterested for now.  Long ago I reserved the "rattailproject" username in GH just in case I ever change my mind, but I'm not there yet.  I have probably 25 repos so could mirror just a subset maybe, but all that seems simpler to keep self-hosted despite the lack of GH exposure.

It really highlights the "network effect" and "walled garden" etc. - I want to support FOSS by using it to self-host my own code, but "nobody" else wants me to b/c they'd prefer GH.  Oh well...

**Comment by lgedgar** [comment]
I guess I should add, that I'd be more amenable to doing things differently if there were more than just the one (me) developer...  That's kind of a chicken vs. egg I suppose.

**Pull request closed without merging**
